# Generated by Django 5.0.8 on 2024-08-09 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='ExpenseData',
        ),
        migrations.RenameModel(
            old_name='Income',
            new_name='IncomeData',
        ),
    ]
